### ISSUE TITLE
Code hands on backtest when dates are added.

### ISSUE THREAD

**Issue by biomechman** [10mohi6/oanda-bot-python#2]
Hi there,

As the title says, it hangs, never finishes, when I use this:

```
from oanda_bot import Bot

class MyBot(Bot):
    def strategy(self):
        rsi = self.rsi(period=5)
        ema = self.ema(period=10)
        lower = ema - (ema * 0.001)
        upper = ema + (ema * 0.001)
        self.buy_entry = (rsi < 40) & (self.df.C < lower)
        self.sell_entry = (rsi > 60) & (self.df.C > upper)
        self.sell_exit = ema > self.df.C
        self.buy_exit = ema < self.df.C
        self.units = 1000 # currency unit (default=10000)
        self.take_profit = 20 # take profit pips (default=0 take profit none)
        self.stop_loss = 10 # stop loss pips (default=0 stop loss none)
        

MyBot(
    account_id='<acc id>',
    access_token='<token>',
    instrument='USD_JPY',
    granularity='H1', # 1 hour candlestick
).backtest(from_date="2020-12-31", to_date="2021-1-31", filename="backtest.png")
```

When I CTRL+C, it returns this:

```
Traceback (most recent call last):
  File "F:\...\advancedBacktest.py", line 18, in <module>
    MyBot(
  File "F:\Python3\...\oanda_bot.py", line 380, in backtest
    self._candles(from_date=from_date, to_date=to_date)
  File "F:\Python3\...\oanda_bot.py", line 125, in _candles
    time.sleep(0.5)
KeyboardInterrupt
```

If I run without time constraints, it runs to completion in a matter of seconds.
Any ideas what the issue might be?

**Comment by RealMithrandir** [comment]
Hi biomechman!

I was having a similar issue, and if you removed `filename="backtest.png` option the code will complete with the included date range. 

Something like `.backtest(from_date="2020-7-7", to_date="2020-7-21")` worked for me. I could then save the file (if wanted) from the Matplotlib visualization.

I'm haven't dug into any of the possible underlying causes, but that solved it in the short term for me.

**Comment by biomechman** [comment]
That worked, many thanks!
